[connections.azure_sql]
server = "tcp:ddcbi.database.windows.net"
database = "DEV_ddc_datawarehouse"
username = "admin_ddc"
password = "2O*7hlV^Ho!5"
driver = "ODBC Driver 17 for SQL Server"

[mail.smtp]
host = "smtp.example.com"
port = 587
username = "usuario"
password = "clave"
from_email = "no-reply@ddc.cl"
from_name = "Planilla Fruta Comercial"
use_tls = true
use_ssl = false
